name: Build and Deploy UPOD.API

on:
  push:
    branches:
      - main

env: 
    IMAGE_TAG: "latest"
    IMAGE: "upod.api"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Login to Docker Hub
          run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        
        - name: Build Docker image
          run: docker build -t ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG .

        - name: Push Docker image to Docker Hub
          run: docker push ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG
  
  deploy:
     needs: build
     runs-on: ubuntu-latest
         
     steps:
     - name: Connect to EC2 Instance, update Docker
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.EC2_PRIVATE_KEY }}
         script: |
             sudo su
             docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
             docker stop ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG || true
             docker rm ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG || true
             docker rmi ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG || true
             docker pull kanatsumi2003/upod.api:latest
             docker run -p 8082:80 ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG
